packaging_format = 2

id = "headscale"
name = "Headscale"
description.en = "Open-source implementation of the Tailscale control server, a WireGuard-based VPN"

version = "0.22.3~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "BSD-3-Clause"
admindoc = "https://headscale.net/"
userdoc = "https://tailscale.com/kb/"
code = "https://github.com/juanfont/headscale"
website = "https://headscale.net/"
cpe = "cpe:2.3:a:tailscale:tailscale"
fund = "https://ko-fi.com/headscale"

[integration]
yunohost = ">= 11.0.0"
architectures = "all"
multi_instance = false
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.dex_domain]
    type = "domain"
    ask.en = "Choose the domain to install Dex on."
    help.en = "It should be different than Headscale's domain"

    [install.dex_path]
    type = "path"
    ask.en = "Choose the path to install Dex on."
    default = "/dex"

    [install.base_domain]
    type = "string"
    ask.en = "Choose the base domain for Headscale's MagicDNS feature"
    help.en = "MagicDNS will allow you to access your hosts with a domain like `myhost.username.basedomain.tld`. It can be from a fake TLD, but beware of conflicts."

[resources]
    [resources.sources.main]
    rename = "headscale"

    i386.url = "https://github.com/juanfont/headscale/releases/download/v0.22.3/headscale_0.22.3_linux_386"
    i386.sha256 = "5e1c23c2ca269041d1040e273d9f164c3703d3b7c38aea5a293c8059b24d9712"
    amd64.url = "https://github.com/juanfont/headscale/releases/download/v0.22.3/headscale_0.22.3_linux_amd64"
    amd64.sha256 = "41eb475ba94d2f4efdd5b90ca76d3926a0fc0b561baabf6190ca32335c9102d2"
    arm64.url = "https://github.com/juanfont/headscale/releases/download/v0.22.3/headscale_0.22.3_linux_arm64"
    arm64.sha256 = "c36b469a30e87efc6616abd7f8df429de2a11896d311037580ac0b9c2f6b53a6"
    armhf.url = "https://github.com/juanfont/headscale/releases/download/v0.22.3/headscale_0.22.3_linux_armv7"
    armhf.sha256 = "4711fd03c9f5d814eb4c85be9939f167ce7aa40510cda2133c9f63810ead395d"
    armel.url = "https://github.com/juanfont/headscale/releases/download/v0.22.3/headscale_0.22.3_linux_armv5"
    armel.sha256 = "3a983ea320b05372b5493ece01bab1252907e0864a26f1857dbcd7307dfc463f"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.i386 = ".*_linux_386$"
    autoupdate.asset.amd64 = ".*_linux_amd64$"
    autoupdate.asset.arm64 = ".*_linux_arm64$"
    autoupdate.asset.armhf = ".*_linux_armv7$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080
    metrics.default = 9090
    grpc.default = 50443

# Disabled, cf. config file
#    [resources.database]
#    type = "postgresql"
