packaging_format = 2

id = "headscale"
name = "Headscale"
description.en = "Tailscale control server implementation, a WireGuard-based VPN"
description.fr = "Implémentation du serveur de contrôle Tailscale, un VPN basé sur WireGuard"

version = "0.26.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "BSD-3-Clause"
admindoc = "https://headscale.net/"
userdoc = "https://tailscale.com/kb/"
code = "https://github.com/juanfont/headscale"
website = "https://headscale.net/"
cpe = "cpe:2.3:a:tailscale:tailscale"
fund = "https://ko-fi.com/headscale"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.dex]
    type = "app"
    filter = "match(id, '^(dex)(__[0-9+])?$')"
    ask.en = "Select the Dex app that will handle authentication for Headscale."
    ask.fr = "Sélectionnez l'app Dex qui gérera l'authentification pour Headscale."
    help.en = "You need to have at least one instance of Dex installed beforehand on your server."
    help.fr = "Vous devez avoir au moins une instance de Dex préalablement installée sur votre serveur."

    [install.domain]
    type = "domain"
    help.en = "Headscale requires a dedicated domain, with no other app installed on it."
    help.fr = "Headscale nécessite un domaine dédié, avec aucune autre app installée dessus."

    [install.base_domain]
    type = "string"
    ask.en = "Choose the base domain for Headscale's MagicDNS feature"
    ask.fr = "Choisissez le domaine de base pour la fonctionnalité MagicDNS de Headscale"
    help.en = "MagicDNS will allow you to access your hosts with a domain like `myhost.username.basedomain.tld`. It can be from a fake TLD, but beware of conflicts."
    help.fr = "MagicDNS vous permettra d'accéder à vos hôtes avec un domaine tel que 'monhôte.nomutilisateur.domainedebase.tld'. Il peut s'agir d'un faux TLD, mais attention aux conflits."

[resources]
    [resources.sources.main]
    rename = "headscale"

    i386.url = "https://github.com/juanfont/headscale/releases/download/v0.26.0/headscale_0.26.0_linux_386"
    i386.sha256 = "9130c99ff1061b51f09c1b27c4782879afa067ce010720749480b529ddb4a1cc"
    amd64.url = "https://github.com/juanfont/headscale/releases/download/v0.26.0/headscale_0.26.0_linux_amd64"
    amd64.sha256 = "2b5907b486be5ab7088962afe1945c9b7299729bae77c09acf24d0ca7194351e"
    arm64.url = "https://github.com/juanfont/headscale/releases/download/v0.26.0/headscale_0.26.0_linux_arm64"
    arm64.sha256 = "5e7b63599165c65d405a8421da4e69c0ce98a9897f9e4eac12eb757f63192b1f"
    armhf.url = "https://github.com/juanfont/headscale/releases/download/v0.26.0/headscale_0.26.0_linux_armv7"
    armhf.sha256 = "e137f277fbaca540a8abb0aa9d381533c304e7ed0d7bf8ccf60b38c8dba1ccc4"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.i386 = ".*_linux_386$"
    autoupdate.asset.amd64 = ".*_linux_amd64$"
    autoupdate.asset.arm64 = ".*_linux_arm64$"
    autoupdate.asset.armhf = ".*_linux_armv7$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.protected = true

    [resources.ports]
    main.default = 8080
    metrics.default = 9090
    grpc.default = 50443
    stun.default = 3478
    stun.exposed = "UDP"

    [resources.apt]
    packages = "ethtool"
