packaging_format = 2

id = "headscale"
name = "Headscale"
description.en = "Tailscale control server implementation, a WireGuard-based VPN"
description.fr = "Implémentation du serveur de contrôle Tailscale, un VPN basé sur WireGuard"

version = "0.24.3~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "BSD-3-Clause"
admindoc = "https://headscale.net/"
userdoc = "https://tailscale.com/kb/"
code = "https://github.com/juanfont/headscale"
website = "https://headscale.net/"
cpe = "cpe:2.3:a:tailscale:tailscale"
fund = "https://ko-fi.com/headscale"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.dex_domain]
    type = "domain"
    ask.en = "Choose the domain to install Dex on"
    ask.fr = "Choisissez le domaine sur lequel installer Dex"
    help.en = "It should be different than Headscale's domain"
    help.fr = "Cela devrait être différent du domaine de Headscale"

    [install.dex_path]
    type = "path"
    ask.en = "Choose the path to install Dex on"
    ask.fr = "Choisissez le chemin sur lequel installer Dex"
    default = "/dex"

    [install.base_domain]
    type = "string"
    ask.en = "Choose the base domain for Headscale's MagicDNS feature"
    ask.fr = "Choisissez le domaine de base pour la fonctionnalité MagicDNS de Headscale"
    help.en = "MagicDNS will allow you to access your hosts with a domain like `myhost.username.basedomain.tld`. It can be from a fake TLD, but beware of conflicts."
    help.fr = "MagicDNS vous permettra d'accéder à vos hôtes avec un domaine tel que 'monhôte.nomutilisateur.domainedebase.tld'. Il peut s'agir d'un faux TLD, mais attention aux conflits."

[resources]
    [resources.sources.main]
    rename = "headscale"

    i386.url = "https://github.com/juanfont/headscale/releases/download/v0.24.3/headscale_0.24.3_linux_386"
    i386.sha256 = "50bee83ee62db7d5f190439903e6f4cb0693277dfb914c93c600b57065de5a00"
    amd64.url = "https://github.com/juanfont/headscale/releases/download/v0.24.3/headscale_0.24.3_linux_amd64"
    amd64.sha256 = "d6dcb26502cde796f3d7ccf3c250b29bb71b4dc6074fc3a58d719feb07d5d63c"
    arm64.url = "https://github.com/juanfont/headscale/releases/download/v0.24.3/headscale_0.24.3_linux_arm64"
    arm64.sha256 = "d381a6f75775ce7c71da326a68e556305af4c50babf55b47770cb03f92a5d7eb"
    armhf.url = "https://github.com/juanfont/headscale/releases/download/v0.24.3/headscale_0.24.3_linux_armv7"
    armhf.sha256 = "49f3be918a84d2eb9475c4b8e00f4c1dfd803ce24a47d714d4d2aad226d4b2d1"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.i386 = ".*_linux_386$"
    autoupdate.asset.amd64 = ".*_linux_amd64$"
    autoupdate.asset.arm64 = ".*_linux_arm64$"
    autoupdate.asset.armhf = ".*_linux_armv7$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.protected = true

    [resources.ports]
    main.default = 8080
    metrics.default = 9090
    grpc.default = 50443
    stun.default = 3478
    stun.exposed = "UDP"

    [resources.apt]
    packages = "ethtool, gawk"
