packaging_format = 2

id = "headscale"
name = "Headscale"
description.en = "Tailscale control server implementation, a WireGuard-based VPN"
description.fr = "Implémentation du serveur de contrôle Tailscale, un VPN basé sur WireGuard"

version = "0.29.2~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "BSD-3-Clause"
admindoc = "https://headscale.net/"
userdoc = "https://tailscale.com/kb/"
code = "https://github.com/juanfont/headscale"
website = "https://headscale.net/"
cpe = "cpe:2.3:a:tailscale:tailscale"
fund = "https://ko-fi.com/headscale"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.dex]
    type = "app"
    filter = "match(id, '^(dex)(__[0-9+])?$')"
    ask.en = "Select the Dex app that will handle authentication for Headscale."
    ask.fr = "Sélectionnez l'app Dex qui gérera l'authentification pour Headscale."
    help.en = "You need to have at least one instance of Dex installed beforehand on your server."
    help.fr = "Vous devez avoir au moins une instance de Dex préalablement installée sur votre serveur."

    [install.domain]
    type = "domain"
    help.en = "Headscale requires a dedicated domain, with no other app installed on it."
    help.fr = "Headscale nécessite un domaine dédié, avec aucune autre app installée dessus."

    [install.base_domain]
    type = "string"
    ask.en = "Choose the base domain for Headscale's MagicDNS feature"
    ask.fr = "Choisissez le domaine de base pour la fonctionnalité MagicDNS de Headscale"
    help.en = "MagicDNS will allow you to access your hosts with a domain like `myhost.username.basedomain.tld`. It can be from a fake TLD, but beware of conflicts."
    help.fr = "MagicDNS vous permettra d'accéder à vos hôtes avec un domaine tel que 'monhôte.nomutilisateur.domainedebase.tld'. Il peut s'agir d'un faux TLD, mais attention aux conflits."

[resources]
    [resources.sources.main]
    rename = "headscale"

    amd64.url = "https://github.com/juanfont/headscale/releases/download/v0.29.2/headscale_0.29.2_linux_amd64"
    amd64.sha256 = "858ef94bca9ecdfc742c24119c831e437e1b75691fdd5041be4059db1a38aac0"
    arm64.url = "https://github.com/juanfont/headscale/releases/download/v0.29.2/headscale_0.29.2_linux_arm64"
    arm64.sha256 = "7f458586fcb4ba5832e4fa7b097948ec99fbca2bb4dd02b335a379f78e7807ac"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*_linux_amd64$"
    autoupdate.asset.arm64 = ".*_linux_arm64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.protected = true

    [resources.ports]
    main.default = 8080
    metrics.default = 9090
    grpc.default = 50443
    stun.default = 3478
    stun.exposed = "UDP"

    [resources.apt]
    packages = "ethtool"
