packaging_format = 2

id = "headscale"
name = "Headscale"
description.en = "Open-source implementation of the Tailscale control server, a WireGuard-based VPN"

version = "0.23.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "BSD-3-Clause"
admindoc = "https://headscale.net/"
userdoc = "https://tailscale.com/kb/"
code = "https://github.com/juanfont/headscale"
website = "https://headscale.net/"
cpe = "cpe:2.3:a:tailscale:tailscale"
fund = "https://ko-fi.com/headscale"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.dex_domain]
    type = "domain"
    ask.en = "Choose the domain to install Dex on."
    help.en = "It should be different than Headscale's domain"

    [install.dex_path]
    type = "path"
    ask.en = "Choose the path to install Dex on."
    default = "/dex"

    [install.base_domain]
    type = "string"
    ask.en = "Choose the base domain for Headscale's MagicDNS feature"
    help.en = "MagicDNS will allow you to access your hosts with a domain like `myhost.username.basedomain.tld`. It can be from a fake TLD, but beware of conflicts."

[resources]
    [resources.sources.main]
    rename = "headscale"

    i386.url = "https://github.com/juanfont/headscale/releases/download/v0.23.0/headscale_0.23.0_linux_386"
    i386.sha256 = "1be6e0df6dd013ced010537cc393674b629d0a9b9554ab0484b84153093ed508"
    amd64.url = "https://github.com/juanfont/headscale/releases/download/v0.23.0/headscale_0.23.0_linux_amd64"
    amd64.sha256 = "d9193dad4b070b9b3f6d54c8f14366952944b6e917672c0bc1dfd8f5491287a7"
    arm64.url = "https://github.com/juanfont/headscale/releases/download/v0.23.0/headscale_0.23.0_linux_arm64"
    arm64.sha256 = "99fa9b2944c50759882b578e78aa11968d6fdec9bbfeced88237a1138b89e9fe"
    armhf.url = "https://github.com/juanfont/headscale/releases/download/v0.23.0/headscale_0.23.0_linux_armv7"
    armhf.sha256 = "c6c285d6b054bfcf74c8afa6b4561d4b1cb00fd0e4dea26bc6fe616498e2c77d"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.i386 = ".*_linux_386$"
    autoupdate.asset.amd64 = ".*_linux_amd64$"
    autoupdate.asset.arm64 = ".*_linux_arm64$"
    autoupdate.asset.armhf = ".*_linux_armv7$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false
    main.allowed = "visitors"
    main.protected = true

    [resources.ports]
    main.default = 8080
    metrics.default = 9090
    grpc.default = 50443

    [resources.apt]
    packages = "gawk"
