#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    exclude = [ "install.private", "change_url" ]

    # ------------
    # Tests to run
    # ------------

    preinstall = """
    sudo yunohost tools update apps
    sudo yunohost domain add dex.domain.tld
    sudo yunohost app install https://github.com/YunoHost-Apps/dex_ynh/tree/oneapptorulethemall -f -a "domain=dex.domain.tld&path=/&oidc_name=&oidc_secret=&oidc_callback"
    """

    preupgrade = """
    sudo yunohost app upgrade dex -u https://github.com/YunoHost-Apps/dex_ynh/tree/oneapptorulethemall -F
    """

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.dex = "dex"
    args.base_domain = "vpn.internal"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.39d7410baadb32a1f9ae5cece7af39a1206327eb.name = "Upgrade from 0.25.0~ynh1"
