#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_config_remove_logrotate

ynh_config_remove_nginx

yunohost app remove $dex_app

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_script_progression "Closing port $port..."
	ynh_hide_warnings yunohost firewall disallow TCP $port
fi

# Remove dnsmasq configuration
ynh_safe_rm "/etc/dnsmasq.d/$app"

ynh_systemctl --service=dnsmasq --action="reload"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
