#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

if [ ! -f "/etc/dnsmasq.d/$app" ]; then
	# Add dnsmasq configuration to avoid overriding resolvconf
	ynh_config_add --template="dnsmasq" --destination="/etc/dnsmasq.d/$app"
	ynh_systemctl --service="dnsmasq" --action="reload"
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod -R ug+x "$install_dir/headscale"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
# We do not alter the configuration file since admins are encouraged to fine-tune it.
# Except for this one time:
if ynh_app_upgrading_from_version_before 0.23.0~ynh3; then
    ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"
    
    chmod 600 "$install_dir/config.yaml"
    chown $app:$app "$install_dir/config.yaml"
fi

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Control server for the WireGuard-based VPN" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
