#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod -R ug+x "$install_dir/headscale"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
# We do not alter the configuration file since admins are encouraged to fine-tune it.
# Except for this one time:
if ynh_app_upgrading_from_version_before 0.23.0~ynh3; then
    ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"
    
    chmod 600 "$install_dir/config.yaml"
    chown $app:$app "$install_dir/config.yaml"
fi

# Remove deprecated dnsmasq config file that led to issues
if ynh_app_upgrading_from_version_before 0.23.0~ynh4; then
    ynh_safe_rm "/etc/dnsmasq.d/$app"
fi

# Comment out a deprecated configuration line
if ynh_app_upgrading_from_version_before 0.24.2~ynh2; then
    ynh_replace --match=" use_username_in_magic_dns: .*" --replace="  # use_username_in_magic_dns: false" --file="$install_dir/config.yaml"
fi

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add $app --description="Control server for the WireGuard-based VPN" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
